const blogData = [
    {
      id: 1,
      title: "Bill Walsh leadership lessons",
      author: "Alec Whitten",
      date: "1 Jan 2023",
      description: "Learn to transform a team into a 3x Super Bowl winning Dynasty!",
      category: "Leadership",
      image: "https://source.unsplash.com/400x300/?leadership",
    },
    {
      id: 2,
      title: "PM mental models",
      author: "Demi Wilkinson",
      date: "1 Jan 2023",
      description: "Mental models are simple expressions of complex processes.",
      category: "Product",
      image: "https://source.unsplash.com/400x300/?teamwork",
    },
    {
      id: 3,
      title: "What is Wireframing?",
      author: "Candice Wu",
      date: "1 Jan 2023",
      description: "Introduction to Wireframing and its Principles.",
      category: "Design",
      image: "https://source.unsplash.com/400x300/?design",
    },
    {
      id: 4,
      title: "Effective Remote Work Strategies",
      author: "Michael Scott",
      date: "10 Feb 2023",
      description: "How to stay productive while working remotely.",
      category: "Work",
      image: "https://source.unsplash.com/400x300/?remote",
    },
    {
      id: 5,
      title: "AI in 2024: What’s Next?",
      author: "Sophia Lee",
      date: "15 Feb 2023",
      description: "A deep dive into the future of AI and ML.",
      category: "Technology",
      image: "https://source.unsplash.com/400x300/?ai",
    },
    {
      id: 6,
      title: "Why UX Matters",
      author: "John Doe",
      date: "20 Feb 2023",
      description: "Understanding the importance of User Experience.",
      category: "UX",
      image: "https://source.unsplash.com/400x300/?ux",
    },
    {
      id: 7,
      title: "Cryptocurrency Trends in 2024",
      author: "Alice Roberts",
      date: "25 Feb 2023",
      description: "Exploring the latest trends in crypto and blockchain.",
      category: "Finance",
      image: "https://source.unsplash.com/400x300/?crypto",
    },
    {
      id: 8,
      title: "The Power of Habit Formation",
      author: "James Clear",
      date: "1 Mar 2023",
      description: "How to build habits that last a lifetime.",
      category: "Self-Improvement",
      image: "https://source.unsplash.com/400x300/?habits",
    },
    {
      id: 9,
      title: "Scaling a Startup Successfully",
      author: "Elon Tusk",
      date: "5 Mar 2023",
      description: "Key steps to scale your startup the right way.",
      category: "Startup",
      image: "https://source.unsplash.com/400x300/?startup",
    },
    {
      id: 10,
      title: "The Future of Remote Education",
      author: "Mark Johnson",
      date: "10 Mar 2023",
      description: "How online learning is changing the education system.",
      category: "Education",
      image: "https://source.unsplash.com/400x300/?education",
    },{
        id: 7,
        title: "Cryptocurrency Trends in 2024",
        author: "Alice Roberts",
        date: "25 Feb 2023",
        description: "Exploring the latest trends in crypto and blockchain.",
        category: "Finance",
        image: "https://source.unsplash.com/400x300/?crypto",
      },
      {
        id: 8,
        title: "The Power of Habit Formation",
        author: "James Clear",
        date: "1 Mar 2023",
        description: "How to build habits that last a lifetime.",
        category: "Self-Improvement",
        image: "https://source.unsplash.com/400x300/?habits",
      },
      {
        id: 9,
        title: "Scaling a Startup Successfully",
        author: "Elon Tusk",
        date: "5 Mar 2023",
        description: "Key steps to scale your startup the right way.",
        category: "Startup",
        image: "https://source.unsplash.com/400x300/?startup",
      },
      {
        id: 10,
        title: "The Future of Remote Education",
        author: "Mark Johnson",
        date: "10 Mar 2023",
        description: "How online learning is changing the education system.",
        category: "Education",
        image: "https://source.unsplash.com/400x300/?education",
      },{
        id: 7,
        title: "Cryptocurrency Trends in 2024",
        author: "Alice Roberts",
        date: "25 Feb 2023",
        description: "Exploring the latest trends in crypto and blockchain.",
        category: "Finance",
        image: "https://source.unsplash.com/400x300/?crypto",
      },
      {
        id: 8,
        title: "The Power of Habit Formation",
        author: "James Clear",
        date: "1 Mar 2023",
        description: "How to build habits that last a lifetime.",
        category: "Self-Improvement",
        image: "https://source.unsplash.com/400x300/?habits",
      },
      {
        id: 9,
        title: "Scaling a Startup Successfully",
        author: "Elon Tusk",
        date: "5 Mar 2023",
        description: "Key steps to scale your startup the right way.",
        category: "Startup",
        image: "https://source.unsplash.com/400x300/?startup",
      },
      {
        id: 10,
        title: "The Future of Remote Education",
        author: "Mark Johnson",
        date: "10 Mar 2023",
        description: "How online learning is changing the education system.",
        category: "Education",
        image: "https://source.unsplash.com/400x300/?education",
      },{
        id: 7,
        title: "Cryptocurrency Trends in 2024",
        author: "Alice Roberts",
        date: "25 Feb 2023",
        description: "Exploring the latest trends in crypto and blockchain.",
        category: "Finance",
        image: "https://source.unsplash.com/400x300/?crypto",
      },
      {
        id: 8,
        title: "The Power of Habit Formation",
        author: "James Clear",
        date: "1 Mar 2023",
        description: "How to build habits that last a lifetime.",
        category: "Self-Improvement",
        image: "https://source.unsplash.com/400x300/?habits",
      },
      {
        id: 9,
        title: "Scaling a Startup Successfully",
        author: "Elon Tusk",
        date: "5 Mar 2023",
        description: "Key steps to scale your startup the right way.",
        category: "Startup",
        image: "https://source.unsplash.com/400x300/?startup",
      },
      {
        id: 10,
        title: "The Future of Remote Education",
        author: "Mark Johnson",
        date: "10 Mar 2023",
        description: "How online learning is changing the education system.",
        category: "Education",
        image: "https://source.unsplash.com/400x300/?education",
      }
  ];
  
  export default blogData;
  